version: '3.8'

services:

  traefik:
    image: traefik:1.7.18
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    command: --docker --web --web.address=:8080
    volumes:
      - ./traefik.toml:/etc/traefik/traefik.toml:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - default

networks:
  default:
    external:
      name: traefik
