version: '2'

services:

  multiple_conda_environments:
    build:
      context: .
    #ports:
    #  - 8888:8888
    command: "--NotebookApp.base_url='multiple_conda_environments'"
    labels:
      - log.level=debug
      - traefik.enable=true
      - traefik.frontend.rule=Host:${HOSTNAME};PathPrefix:/multiple_conda_environments/
      - traefik.frontend.auth.basic=${MULTI_CONDA_HTTP_USER}:${MULTI_CONDA_HTTP_AUTH_PASS_ENC}
    depends_on:
      - traefik
