version: '3.8'

services:

  traefik:
    image: traefik:1.7.18
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    command: -d --web --web.address=:8080
    volumes:
      - ./traefik/traefik.toml:/etc/traefik/traefik.toml:ro
      - /var/run/docker.sock:/var/run/docker.sock