version: '2'

services:

  flask:
    build:
      context: server
      dockerfile: Dockerfile
    container_name: flask
    # ports:
    # Mapping ports should not be done if we do not want to expose the service to the internet
    #  - 5000:5000
    expose:
      - 5000
    depends_on:
      - redis
      - traefik
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:${HOSTNAME};PathPrefix:/flask/
      - traefik.frontend.auth.basic=${FLASK_HTTP_USER}:${FLASK_HTTP_AUTH_PASS_ENC}

  flask_client:
    build:
      context: client
      dockerfile: Dockerfile
    container_name: flask_client
    command: jupyter notebook --port=8888 --ip=0.0.0.0 --NotebookApp.base_url='flask_client' --NotebookApp.token='' --NotebookApp.password=''
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:${HOSTNAME};PathPrefix:/flask_client/
      - traefik.frontend.auth.basic=${FLASK_HTTP_USER}:${FLASK_HTTP_AUTH_PASS_ENC}

  redis:
      image: redis
      container_name: redis


